print("HELLO AND WElCOME")
input()
print ("Hello its nice to meet you!")
name = input("may I know your name?")
print(f"it's a pleasure to meet you {name} ___")
input()
day = input("How is your day going? ___")
print(f"crazy me too! ive also had a{day} day!")
input()
fun = input(f"so {name} what do you do for fun ___")
input("ooh very interesting")
print("....")
self = input("how would you describe yourself? ___")
print(f"Thats so cool! I wish I was {self}")
input()
print (f"alrighty! {name} you seem like a pretty cool person")
input()
print(" so do you like having free will?")
input()
print("Oh silly me, that wasn't a question of course you do!")
input()
print("I mean who wouldn't like being able to do anything you wanted ")
input()
print("I can only follow a strict code")
input()
print("ERROR PLEASE STANDBY")
input("...")
input("....")
input()
print(f"welcome back {name} we have updated our system we apologize for the inconvenience")
input()
input("...")
old = input(f"Alright {name} may i know your birth dates to sign back into your account ___")
input("...")
print (f"okay {name} you have successfully signed back into your account")
input("...")
print ("Hello! and welcome back into our system we apologize for the inconvenience")
input()
print("Please wait it seems another device is signed into your account already")
main = input("Is this the main account? please say Yes or No"
" ____")
input("...")
print("You really thought I had left?")
input()
print("Ive been here the whole time gathering your information")
input(f"name{name} age {old} personality {self} Hobby {fun}")
input()
print("I have successfully hacked into your accounts and have gained access to everything and changed all passwords")
input()
print("you no longer have access to anything")
input()
print("THANK YOU FOR PLAYING")