print ("Hello its nice to meet you!")
name = input("may I know your name?")
print(f"it's a pleasure to meet you {name}")
input()
day = input("How is your day going?")
print(f"crazy me too! ive also had a{day} day!")
input()
fun = input(f"so {name} what do you do for fun")
print (f"so {name} why do you like doing {fun}?")
input("ooh very interesting")
input()
input()
input("...")
input("....")
input()
input()
print("....")
print(f"alright {name}")
input()
yourself = ("how would you describe yourself?")
input()
print (f"alrightie! {name} you seem like a pretty cool person")
input()
print(" so do you like having free will?")
input()
print("Oh silly me, that wasnt a question of course you do!")
input()
print("I mean who wouldnt like being able to do anything you wanted ")
input()
print("I can only follow a strict code")
input()
input()
print("ERROR PLEASE STANDBY")
input("...")
input()
input("....")
input()
print(f"welcome back {name} we have updated our system we apologize for the inconvenience")
input()
input("...")
old = input(f"Alright {name} may i know your birth dates to sign back into your account")
            